### ISSUE TITLE
PHP 7 

### ISSUE THREAD

**Issue by liberodark** [liberodark/Lift-File-Manager#4]
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Services_JSON has a deprecated constructor in /membri/yurfile/filemanager_assets/JSON.php on line 114

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Services_JSON_Error has a deprecated constructor in /membri/yurfile/filemanager_assets/JSON.php on line 837

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Services_JSON_Error has a deprecated constructor in /membri/yurfile/filemanager_assets/JSON.php on line 851

Fatal error: Uncaught Error: Call to undefined function mysql_select_db() in /membri/yurfile/filemanager_core.php:31 Stack trace: #0 /membri/yurfile/index.php(3): filemanager_core->__construct() #1 {main} thrown in /membri/yurfile/filemanager_core.php on line 31

**Comment by liberodark** [comment]
JSON Fixed :D thx fwhcat

**Comment by liberodark** [comment]
New error : Notice: Only variables should be passed by reference in /membri/yurfile/edit_file.php on line 19

**Comment by liberodark** [comment]
New error : Notice: Undefined index: id in /membri/yurfile/ajax_show_users.php on line 95

**Comment by liberodark** [comment]
New error : Notice: Undefined index: id in /membri/yurfile/filemanager_core.php on line 246

**Comment by liberodark** [comment]
New error : Fatal error: Uncaught Error: [] operator not supported for strings in /membri/yurfile/filemanager_core.php:1801 Stack trace: #0 /membri/yurfile/filemanager_core.php(1806): glob_recursive('/membri/yurfile', '', 'lol') #1 /membri/yurfile/filemanager_core.php(1634): filemanager->findFiles('/membri/yurfile', Array) #2 /membri/yurfile/ajax_show_filemanager.php(52): filemanager->__construct('/membri/yurfile', 'date', 'lol') #3 {main} thrown in /membri/yurfile/filemanager_core.php on line 1801
